<script type="text/javascript">
	require([
		'jquery',
	], function(jQuery){
		(function($) {
			$(document).ready(function(){
				$('.action.nav-toggle').click(function(){
					if ($('html').hasClass('nav-open')) {
						$('html').removeClass('nav-open');
						setTimeout(function () {
							$('html').removeClass('nav-before-open');
						}, 300);
					} else {
						$('html').addClass('nav-before-open');
						setTimeout(function () {
							$('html').addClass('nav-open');
						}, 42);
					}
				});
				$('.nav-open .page-wrapper').click(function(){
					$('html').removeClass('nav-open');
					setTimeout(function () {
						$('html').removeClass('nav-before-open');
					}, 300);
				});
			});
		})(jQuery);
	});
	function toggleEl(el, elId){
		require([
			'jquery',
		], function(jQuery){
			(function($) {
				$('#'+elId).toggleClass('active').slideToggle();
				$(el).toggleClass('active');
			})(jQuery);
		});
	}
</script>
