<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php 
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$themeSettings = $themeHelper->getThemeSettings();
?>
<?php 
	$om = \Magento\Framework\App\ObjectManager::getInstance();
	$storeManager = $om->get('Magento\Store\Model\StoreManagerInterface');
	$currentStore = $storeManager->getStore();
	$currentUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>
<?php if($themeSettings['contact_google_map']['display_google_map'] && ($themeSettings['contact_google_map']['address_google_map'] !='')): ?>
	<?php $image = $currentUrl.'map/'.$themeSettings['contact_google_map']['pin_google_map'] ?>
	<div class="map-container nopadding">
		<div id="map" style="height: 401px;">
			<iframe src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d2965.0824050173574!2d-93.63905729999999!3d41.998507000000004!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sWebFilings%2C+University+Boulevard%2C+Ames%2C+IA!5e0!3m2!1sen!2sus!4v1390839289319" width="100%" height="400" frameborder="0" style="border:0"></iframe>
		</div>
	</div>
<?php endif ?>
